language: objective-c
osx_image: xcode9.2
cache:
  directories:
  - Libraries
script:
- xcodebuild -project "$PROJECT" -scheme "$SCHEME" -configuration "$CONFIGURATION"
  -sdk "$SDK" -destination "$DESTINATION" -derivedDataPath build
env:
  matrix:
  - SDK=iphonesimulator CONFIGURATION=Debug ACTION=test
  - SDK=iphonesimulator CONFIGURATION=Release ACTION=test
  global:
  - LANG=en_US.UTF-8
  - LC_ALL=en_US.UTF-8
  - PROJECT=EthereumKit.xcodeproj
  - SCHEME=EthereumKit
  - DESTINATION='name=iPhone 7,OS=11.4'
branches:
  only:
  - master
